### ISSUE TITLE
navigation bar

### ISSUE THREAD

**Issue by ironcamel** [agordon/dancer_bootstrap_fontawesome_template#2]
I think a navigation bar with login/logout/signup functionality would be really useful. Every app I create seems to require that.

These are the links from the email I sent to the dancer mailing list:
http://boilerplate-tudorconstantin.dotcloud.com
https://github.com/tudorconstantin/Mojolicious-Boilerplate

**Comment by agordon** [comment]
A working example is in github, and usable here: http://cowbell.cancan.cshl.edu/dispatch.cgi/navbar_login .

Since I've never used navbar+login, it's ugly as heck.
You probably have better HTML code for that, and I'll be happy to merge it, just update `./views/examples/navbar_login.tt` .

**Comment by ironcamel** [comment]
I'll give it a shot, thanks!
