### ISSUE TITLE
photo gallery/slideshow

### ISSUE THREAD

**Issue by ironcamel** [agordon/dancer_bootstrap_fontawesome_template#3]
I am a little jealous of the photo gallery/slideshow demonstrated at:
http://boilerplate-tudorconstantin.dotcloud.com
https://github.com/tudorconstantin/Mojolicious-Boilerplate

**Comment by agordon** [comment]
No need to be jealous any more :)

http://cowbell.cancan.cshl.edu/dispatch.cgi/photo_carousel

**Comment by ironcamel** [comment]
That's beautiful. Thanks for taking the time to implement this. Any chance you will also add a photo gallery demo in addition to the slideshow? We could just imitate the mojo example.

**Comment by agordon** [comment]
Naveed Massjouni wrote, On 07/05/2012 12:28 PM:

> That's beautiful. Thanks for taking the time to implement this. Any chance you will also add a photo gallery demo in addition to the slideshow? We could just imitate the mojo example.

This was mind-blowingly simple and quick, Dancer is just awesome (Bootstrap isn't too bad, either).

http://cowbell.cancan.cshl.edu/dispatch.cgi/photo_grid

-gordon
