### ISSUE TITLE
how to use onclick on fontawesome icon?

### ISSUE THREAD

**Issue by chenryn** [agordon/dancer_bootstrap_fontawesome_template#8]
I use `<i class="icon-plus"></i>`, but the jQuery `$(".icon-plus").on("click",function(e){alert(e)})` cannot run successful.
I saw "Resource interpreted as Font but transferred with MIME type application/data: "http://myip:3000/fontawesome/font/fontawesome-webfont.woff"." in my Chrome.
And I found another website using bootstrap but no fontawesome can do those actioin on icon-plus etc. They download resources like "/img/glyphicons-halflings.png".

**Comment by agordon** [comment]
I think this is a question best asked on a Font-Awesome/Bootstrap/JQuery related websites, as I have no experience with these issues.
